FROM rocker/rstudio:latest

MAINTAINER Jost Vrabic Koren "jost.koren@bcm.edu"

RUN apt update && apt install -y \
    libz-dev \
    libgeos-dev \
    libxml2 \
    libglpk40 \
    python3-pip \
    python-is-python3

RUN pip install scvi-tools
RUN pip install scanpy

RUN R -e "install.packages('Seurat')"
RUN R -e "install.packages('devtools')"
RUN R -e "install.packages('BiocManager')"
RUN R -e "BiocManager::install(c('LoomExperiment', 'SingleCellExperiment'))"
RUN R -e "devtools::install_github('cellgeni/sceasy')"

EXPOSE 8787

CMD ["/init"]
